---
title: "Project Report - Deforestation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Project Report - Deforestation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Deforestation and carbon balance in Southern Virginia, U.S. between 1990 and 2000

## Introduction

Forest is the largest terrestrial carbon sink stabilizing carbon storage on Earth. Forest also plays a fundamental role in regulating global climate, securing watershed health conditions, sheltering biological diversity, and providing other ecosystem services (Potapov et al., 2017; Hansen et al., 2013). Although forest performs irreplaceable functions in both ecosystem and carbon cycle, about 7-11 million square kilometers of natural forests have been deforested through agricultural expansion and timber harvest during the past 300 years (Foley et al., 2005). Deforestation can affect a wide range of ecological functions, including carbon stocks and biomass accumulations. Forest ecosystem carbon stock, which is closely related to above ground woody biomass, stores carbon sequestered from the atmosphere. In this study, we chose six counties in Southern Virginia to understand the connection among deforestation, carbon, and biomass because forest harvesting events are particularly common in forestland of Virginia. Much more carbon stocks and biomass are removed from this region than the Northern, Rockies, and Southern pacific coast regions (Masek et al., 2011). Specifically, we intend to understand 1) how many forests are deforested in these six counties between 1990 and 2000; 2) how carbon stocks are affected from deforestation; 3) How aboveground woody biomass (AGB) are affected from deforestation.
 
## Data & Methods

### 2.1 Quantifying forest harvest between 1990 and 2000 (Jianing) 

To explore the forest disturbance across our study region, we used the North American Forest Dynamics (NAFD) products derived from Landsat images with a nominal spatial 30 m and forest disturbances mapped at an annual time step. Each annual map has classified pixels showing water, no forest cover, forest cover and forest disturbance that occurred in that year. 
In our project, we used both raster, vector data and tiff images, produced cartographic images and tables and saved our results into png format. So, we loaded the packages: “ geospaar”, “dplyr”, “rgdal”, “ tiff”, “ggplot2”, “here” and “gridExtra”.
we mainly used the functions “st_read”, “st_write”, “raster”, “st_transform”, “crop”, “raster::mask” , “rasterize” and “resample” in our data pre-processing stage. In the analysis step, we used the “zonal”, “plot_noaxes”, “resample”,” tableGrob”, “grid.arrange” functions. While, in the result part, we used “here”, “writeRaster”, “png”, “dev.off “, “knitr::include_graphics” functions. 


### 2.2 Comparing forest carbon stock change between 1990 and 2000 (Novak) 

Forest Carbon Stocks and Fluxes After Disturbance, Southeastern USA, 1990-2010 (novak)
We used Forest Carbon Stocks and Fluxes After Disturbance, Southeastern USA, 1990-2010 dataset to study the carbon stocks and fluxes. We specifically extracted two data files to study the carbon stocks and fluxes in the form of net ecosystem productivity (NEP) in 1990 and 2000. Data was then cropped and masked using a study area raster that we created based on our selection of 6 counties in Virginia. Functions like “resample” and “zonal” are then used to summarize the statistics of the amount of NEP and further compare the results in the two years. Other analyses on amount of NEP in harvested areas and undisturbed areas were also performed.  


### 2.3. Comparing forest biomass change between 1990 and 2000 (Li) 

Biomass data were extracted from the National Aboveground Biomass and Carbon Baseline Dataset (NBCD, Version 2) and Forest Carbon Stocks and Fluxes After Disturbance, Southeastern USA, 1990-2010 dataset. Biomass were compared between 1990 and 2000 for all forest land, the forest harvested land, and the undisturbed land in our study area. A variety of packages are used to pre-process raster and shapefiles and visualize datasets. Besides the packages mentioned in the sections above, I have also used rastervis, tmap, and mapview to visualize my data. Additionally, merge, full_join, and raster calculation are three functions that I haved used but not mentioned in the sections above.  


## 3. Results

### 3.1 Forest area change between 1990 and 2000  (Jianing) 

Figure 1 shows our study region, six counties from Virginia. As we can see from figure 2, the forest extent map of 1990, which represents the forest cover area in 1990 across the study area. The forest harvest map (figure 3) shows the forest degeneration from 1990 to 2000. While, refers to figure 4, most areas of the study region weren’t disturbed during the 10 years. As for the forest harvest percentage map (figure 5), most areas are covered by green, which is in line with the result of the former two maps. Table 1 shows the total forest harvest area in each county. Brunswick county had the biggest forest harvest area (160948 acres) followed by Sussex county (134145 acres), while there were only 68166 acres forest disappeared in Greensville county during the given years. The total forest area in 1990 of Brunswick was the biggest among the six counties (1137933 acres), while the Greensville county, with 545649 acres, had the smallest forest area in 1990. (Refer to table 2). Table 3 shows the forest harvest percentage, Sussex county, with 0.147% percent of forest degeneration, suffered the most severe forest loss during the given year followed by 0.141% percent in Brunswick county and there was only 0.091% forest loss in Mecklenburg county. The three bar graphs (figure6-8) also show the same information as table but in a more visually direct way. 
### 3.2 Forest carbon stock change between 1990 and 2000  (Novak) 

Figure 9 shows a visual representation of the change of net ecosystem productivity (NEP) between 1990 and 2000. Overall, we can see a trend of decreasing amount of NEP from 1990 to 2000. Brunswick County has the largest amount of NEP across all six counties in both 1990 and 2000. The biggest decrease of NEP is also observed in Brunswick County with a decrease of 46,541,717g C m-2year-1 from 1990 to 2000 followed by a decrease of 32,846,791g C m-2year-1 in Lunenberg. 

Further analyses on harvested areas and undisturbed areas show a similar trend of results with Brunswick county having the most amount of NEP and Greensville having the least.

### 3.3 Forest biomass change between 1990 and 2000 (Li) 
Figure 10-12 shows aboveground woody biomass (AGB) in 1990 and 2000 collected from two different datasets. The SE forest carbon stock dataset shows that the total AGB in 1990 and 2000 ranges from about 1 to 11 kg C per square meter. Differently, the NBCD dataset represents a much larger range of AGB estimates for our study area, about 0 to 32 kg C per square meter. One potential reason causing this distinct difference is due to different biomass measuring approaches.   
In Figure 13, the biomass of total forest land is shown to be decreased from 1990 to 2000 because of frequent forest harvesting events in the study region. Since the NBCD dataset provides a much larger estimate of biomass which makes comparison impossible, we decide to ignore it. Figure 14 shows that Brunswick is the county that lost the highest amount of biomass from harvest events, followed by Sussex, Lunenburg, Mecklenburg, Dinwiddie, and Greensville. Figure 15 shows that Mecklenburg maintains the highest undisturbed biomass, followed by Brunswick, Dinwiddie, Lunenberg, Sussex, and Greensville. 

## 4. Discussion and conclusion. 
During the forest dynamics analysis, we learnt many new packages, functions and improved our problem-solving skill. We learnt using the “here” package to locate our files relative to project root. And a “gridExtra” package to arrange our data frame and draw tables. To save our result into the png format, we used the “png” and “dev.off” function. “knitr::include_graphics” function helped us to display our outputs in an easier way. We also tried to use Monitoring Trends in Burn Severity (MTBS) data to filter our forest cover map, but after cropping and masking the data, we found that there was no overlap between these two datasets, which means there is no burned area in our study area. 

In this project, we have met many challenges and uncertainties. Jianing spent a lot of time debugging when she tried to rasterize the study area shapefile and finally found that she missed the resolution value, which reminded her of paying more attention to details. Also, she wanted to emphasize that nobody should forget to resample before using the “zonal” function. Li had trouble building and installing our group project package. She also encountered errors while uploading large files (>100 MB) onto Github. Later on, she learnt to use the “git filter-branch” function to rewrite the git history and only submit files smaller than 100 MB on Github. She also became more familiar with “devtools” after several tries of building R packages.   

In order to develop this project further, we would like to explore the time series trajectory of forest clearing, carbon stock, and biomass change based on the datasets we have. We also want to learn more about the shiny and leaflet frameworks to display our project in a more data-user-friendly way. We also would like to explore the time series trajectory of forest clearing, carbon stock, and biomass change based on the datasets we have. 

## 5.References

Foley, J.A., DeFries, R., Asner, G.P., Barford, C., Bonan, G., Carpenter, S.R., Chapin, F.S., Coe, M.T., Daily, G.C., Gibbs, H.K., Helkowski, J.H., Holloway, T., Howard, E.A., Kucharik, C.J., Monfreda, C., Patz, J.A., Prentice, C., Ramankutty, N., & Snyder, P.K. (2005). Global Consequences of Land Use. Science, 309, 570-574. 
Hansen, M.C., Potapov, P., Moore, R., Hancher, M., Turubanova, S., Tyukavina, A., Thau, D., Stehman, S., Goetz, S., Loveland, T., Kommareddy, A., Egorov, A., Chini, L., Justice, C.O., & Townshend, J. (2013). High-Resolution Global Maps of 21st-Century Forest Cover Change. Science, 342, 850-853.
Masek, J. G., Cohen, W. B., Leckie, D., Wulder,, M. A., Vargas, R., de Jong, B., et al. (2011). Recent rates of forest harvest and conversion in North America. Journal of Geophysical Research, 116(G4), 1–22. http://dx.doi.org/10.1029/2010JG001471.
Potapov, P.V., Hansen, M.C., Laestadius, L., Turubanova, S., Yaroshenko, A., Thies, C., Smith, W., Zhuravleva, I., Komarova, A., Minnemeyer, S., & Esipova, E. (2017). The Last Frontiers of Wilderness: Tracking Loss of Intact Forest Landscapes from 2000 to 2013. Science Advances, 3, 1-13.


